version: '3.8'
services:
  sc_backend:
    container_name: backend_school
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "6071:3000" 
    volumes:
      - .:/app
      - ./cdn:/app/cdn
    env_file:
      - .env
    command: npm run start:prod
    networks:
      - webnet
    restart: always

  sc_nginx:
    container_name: nginx_school
    image: nginx:latest
    expose:
      - 80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/etc/ssl/cert.pem:/etc/ssl/cert.pem:ro
      - ./docker/nginx/etc/ssl/key.pem:/etc/ssl/key.pem:ro
      - ./docker/nginx/etc/ssl/cloudflare.crt:/etc/ssl/cloudflare.crt:ro
      - ./cdn:/srv
    networks:
      - webnet
    restart: always

networks:
  webnet:
    driver: bridge
    